### PR TITLE
Integrate ishikawa

### PR DESCRIPTION
**Pull request by vitorenesduarte**

### CODE REVIEW

**Comment by cmeiklejohn** [comment]
So, did you verify that ishikawa is actually working correctly, then?

**Comment by vitorenesduarte** [comment]
@cmeiklejohn The pure op tests we have [are passing](https://github.com/vitorenesduarte/lsim/pull/2).
@gyounes please merge this when you check if all the trcb stuff we had here are in ishikawa

**Comment by cmeiklejohn** [comment]
Does this mean that ishikawa is working correctly?

**Comment by vitorenesduarte** [comment]
The pure op tests there were passing were the ones where the topology was a line.
If the topology has cycles (HyParView), the tests do not finish.
cc @gyounes

**Comment by vitorenesduarte** [comment]
Just pushed a new branch to ishikawa ([PR](https://github.com/lasp-lang/ishikawa/pull/13)) that:
- disables resend
- fixes some pattern matching

and the pure op tests we have are passing.

**Comment by vitorenesduarte** [comment]
The tests pass with 3 nodes (in complete graph).
But start failing with 5 nodes (no longer full membership)

**Pull request merged**
